### PR TITLE
Fixes at-expiration values being `nan`

### LINKED ISSUE #89: Options at-expiration return `nan`
I am using `tf-quant-finance` for plotting option values and greeks.  When plotting at-expiration (so `expiries=0`) most of the models return `nan` for some or all prices.  Is this intended behavior, in which case I should wrap my calls to `tf-quant-finance` with some code to counter this, or is this something that could be changed?

This issue shows up for:
* Bjerksund-Stensland with `modified_boundary=True` for all prices on a call, but only out-of-the-money prices on puts
* Adesi-Whaley for out-of-the-money prices on calls only
* Binomial for all options (American or European, calls or puts)

Only Black-Scholes-Merton and Bjerksund-Stensland with `modified_boundary=False` are not affected by this.

I could submit a PR to fix this issue, but before I do the work I want to make sure that this is a bug and not a feature.

### PR DESCRIPTION
**Pull request by alembcke**
Fixes #89.  Fixes at-expiration values being `nan` for certain option models.

Tests were run to ensure that values prior to expiration are not affected.  Tests were also run to ensure that execution time was not impacted materially.  Bazel tests also passed for all modified functions.

### CODE REVIEW

**Comment by cyrilchim** [comment]
Could you please sync your version to head as well to fix current merge failure?

**Comment by alembcke** [comment]
I synced my fork and I see there is a new commit here, but it looks like copybara is still failing.  Is there anything else I need to do?

**Comment by cyrilchim** [comment]
Thank you, Alex! Could  you please run git squash?

**Comment by alembcke** [comment]
I haven't added in the test yet, I only synced my fork with master.  I will have the tests done soon and then I will squash the commits and force push.

**Comment by alembcke** [comment]
OK, test added and squashed commits, I hope I did it right.

**Pull request merged**
